
const countries = {

    "ps-AF": "Afghanistan",
    "kab-DZ": "Algeria",
    "en-AS": "Amer.Samoa",
    "en-AI": "Anguilla",
    "en-AR": "Argentina",
    "en-AU": "Australia",
    "en-AT": "Austria",
    "az-AZ": "Azerbaijan",
    "en-BS": "Bahamas",
    "bn-BGD": "Bangla",
    "ccp-BD": "Bang. Chakma",
    "be-BY": "Belarus",
    "nl-BE": "Belgium",
    "dz-BT": "Bhutan",
    "en-BR": "Brazil",
    "ms-BN": "Brunei",
    "en-CA": "Canada",
    "fr-CF": "Cen.A.Republic",
    "en-G8": "English",
    "en-150": "Europe",
    "fi-FI": "Finland",
    "br-FR": "France",
    "ksh-DE": "Germany",
    "fr-HT": "Haiti",
    "yue-HK": "Hong Kong",
    "en-IS": "Iceland",
    "as-INc": "India",
    "ca-IT": "Italy",
    "en-JP": "Japan",
    "ebu-KE": "Kenya",
    "en-MY": "Malaysia",
    "bm-ML": "Mali",
    "Mexico": "Mexico",
    "ar-MA": "Morocco",
    "my-MM": "Myanmar",
    "naq-NA": "Namibia",
    "ne-NP": "Nepal",
    "nl-NL": "Netherlands",
    "en-NZ": "New Zealand",
    "ko-KP": "North Korea",
    "ar-OM": "Oman",
    "en-PK": "Pakistan",
    "qu-PE": "Peru",
    "ceb-PH": "Philippines",
    "en-PT": "Portugal",
    "ar-QA": "Qatar",
    "ba-RU": "Russia",
    "ar-SA": "Saudi Arabia",
    "en-SA": "Arabia-English",
    "fr-SN": "Senegal",
    "zh-SG": "Singapore",
    "af-ZA": "South Africa",
    "ast-ES": "Spain",
    "en-CH": "Switzerland",
    "zh-TW": "Taiwan",
    "en-TR": "Turkey",
    "cgg-UG": "Uganda",
    "en-UA": "Ukraine",
    "ar-AE": "U.Arab Emirates",
    "kw-GB": "United Kingdom",
    "chr-US": "United States",
    "es-UY": "Uruguay",
    "vi-VN": "Vietnam",
    "ar-001": "World-Arabic",
    "": "World	English",
    "en-001": "World	English",
    "ar-YE": "Yemen",
    "en-ZW": "Zimbabwe"

};




